
// Do not edit this file, it is auto-generated at build time!
// See scripts/register-color-provider.ts to modify the generation of this file.
import { HslColorProvider } from '../shared/providers/hsl-color-provider';
import { RgbColorProvider } from '../shared/providers/rgb-color-provider';

export const providers = new Map<string, any>();
providers.set('hsl', HslColorProvider);
providers.set('rgb', RgbColorProvider);
