import fs from 'fs';
import path from 'path';
import chokidar from 'chokidar';

const colorProviders: string = path.resolve('temp/colorRegisteredProvider.ts');
const providersList: string = 'shared/providers';
const namingConvention: string = 'color-provider.ts';

const isWatch: boolean = process.argv.some((arg) => arg === '--watch');

if (isWatch) {
    watchColorProviders();
} else {
    writeColorProviders();
}

function watchColorProviders(): void {
    // eslint-disable-next-line no-console
    console.log(`Watching for changes to component factory sources in ${providersList}...`);

    chokidar
        .watch(providersList, { ignoreInitial: true, awaitWriteFinish: true })
        .on('add', writeColorProviders)
        .on('unlink', writeColorProviders);
}

function writeColorProviders(): void {
    const componentFactory = susribeColorProviders();
    // eslint-disable-next-line no-console
    console.log(`Writing component factory to ${colorProviders}`);
    fs.writeFileSync(colorProviders, componentFactory, { encoding: 'utf8' });
}

function capitalize(word: string): string {
    return word.replace(/\w/, (firstLetter) => firstLetter.toUpperCase());
}

function camalize(word: string) {
    return word.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase());
}

function susribeColorProviders() {
    const imports: Array<string> = [];
    const registrations: Array<string> = [];
    const providers: Array<string> = [];

    fs.readdirSync(providersList).forEach((srcSubFolder: string) => {
        const srcSubFolderFullPath: string = path.join(providersList, srcSubFolder);
        const providerFolder = srcSubFolderFullPath.replace(/(\\)/g, '/');
        // eslint-disable-next-line no-console
        if (!fs.existsSync(srcSubFolderFullPath) && srcSubFolderFullPath.indexOf(namingConvention) < 0) return;
        const findNamingConvention = new RegExp(namingConvention, 'g');
        const importVarName = capitalize(camalize(srcSubFolder.replace(/.ts/, '')))
            .replace(/[^\w]+/g, '');
        const providerSymbol = srcSubFolder
            .replace(findNamingConvention, '')
            .replace(/[^\w]+/g, '');
        // eslint-disable-next-line no-console
        console.debug(`Registering component ${importVarName}`);
        providers.push(importVarName);
        imports.push(`import { ${importVarName} } from '../${providerFolder.replace(/.ts/, '')}';`);
        registrations.push(`providers.set('${providerSymbol}', ${importVarName});`);
    });

    return `
// Do not edit this file, it is auto-generated at build time!
// See scripts/register-color-provider.ts to modify the generation of this file.
${imports.join('\n')}

export const providers = new Map<string, any>();
${registrations.join('\n')}
`;
}

export {};
